apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-myapp-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/NicholasMariga/argocd-application-config.git
    targetRevision: HEAD
    path: apache                
  destination:
    server: https://kubernetes.default.svc
    namespace: apache-myapp    

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true