apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-myapp
  namespace: apache-myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-myapp
  template:
    metadata:
      labels:
        app: apache-myapp 
    spec:
      containers:
      - name: apache-myapp
        image: httpd:2.4        
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/local/apache2/htdocs/    
      volumes:
      - name: html-volume
        configMap:
          name: apache-html                    
